version: '3.8'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '10.6.0.1:81:81'
      - '443:443'
    networks:
      - reverse-proxy
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
  reverse-proxy:
    external: yes
